### ISSUE TITLE
[ArrayShape] doesn't work for structure inside the array

### ISSUE THREAD

**Issue by hantc** [JetBrains/phpstorm-attributes#18]
Hello, pseudocode:

```
    #[ArrayShape(['soldCount' => 'int', 'bookId' => 'int'])]
    public function foo(): array
    {
        $arr = [];

        $arr[] = [
            'soldCount' => 123,
            'bookId' => 453478,
        ];

        $arr[] = [
            'soldCount' => 22,
            'bookId' => 7863,
        ];


        return $arr;
    }
```

I'm not able to make phpstorm to suggest 'soldCount' and 'bookId' inside foreach. Is there any way how to define ArrayShape for structure inside list of items in array?

```
foreach ($this->foo() as $item) {
   echo $item['soldCount']; // phpstorm doesn't suggest
}
```

**Comment by jonnywilliamson** [comment]
Actually a bit freaky as I was coming here to report very similar issue and you've posted only 25mins before me.

The issue is with regards having an `array` with just `keys` => `values` vs having an `array` that contains OTHER `arrays` with `keys` => `values`.


Take this code, it shows an single array being returned with only `keys`=>`values`.  Everything works:

```php
#[ArrayShape(
    [
        'id'   => 'int',
        'name' => 'string',
        'foo'  => Exception::class,
    ])]
function users(): array
{
    return [
        'id'   => 3,
        'name' => 'Harry',
        'foo'  => InvalidArgumentException::class,
    ];
}

$users = users();
$users['foo']-><CURSOR>;

```


In PHPStorm we get autocomplete:
<img width="598" alt="CleanShot 2022-01-30 at 13 52 19@2x" src="https://user-images.githubusercontent.com/2513663/151702752-7d22fc8b-5c77-4f3f-9818-5f71912e14af.png">

<img width="773" alt="CleanShot 2022-01-30 at 13 52 44@2x" src="https://user-images.githubusercontent.com/2513663/151702755-8ec70755-cd31-4a5c-a368-0b0b472d7851.png">



But what should we do if we return a collection of arrays (an array containing many arrays)? How do we use `Arrayshape` to say every single item in this array, is an array with a shape like this?

Here was my attempt:

```php
#[ArrayShape(
    [
        [
            'id'   => 'int',
            'name' => 'string',
            'foo'  => Exception::class,
        ],
    ]
)]
function users(): array
{
    return [
        [
            'id'   => 1,
            'name' => 'Tom',
            'foo'  => Exception::class,
        ],
        [
            'id'   => 2,
            'name' => 'Dick',
            'foo'  => Exception::class,
        ],
    ];
}

$users = users();
$users['<CURSOR>']
```


But no joy at all in PHPStorm.

<img width="579" alt="CleanShot 2022-01-30 at 14 03 58@2x" src="https://user-images.githubusercontent.com/2513663/151702990-ba63b9b9-c041-48a8-b418-211ea729044e.png">



Is this even possible?

**Comment by wbars** [comment]
Hello, thank you for the suggestion. Nested arrays without keys are not supported at this point. We created a feature request to follow: https://youtrack.jetbrains.com/issue/WI-65168
