### ISSUE TITLE
ExpectedValues do not support enum class

### ISSUE THREAD

**Issue by diloabininyeri** [JetBrains/phpstorm-attributes#21]
ExpectedValues do not support enum class, sample code below
```php

use JetBrains\PhpStorm\ExpectedValues;

enum Color:string
{
    case RED='red';
    case BLUE='blue';
}


function test(#[ExpectedValues(valuesFromClass: Color::class)] string $color):string
{
    return $color;
}


test();//autocomplete not working yet


```

**Comment by isfedorov** [comment]
There was such YT ticket https://youtrack.jetbrains.com/issue/WI-60485/Add-possibility-to-pass-Enumcases-as-parameter-of-ExpectedValues-attribute but it was declined because the reasoning wasn't clear, why one want to use ExpectedValues attribute instead of regular type hint of enum's class. If you have some other reasoning, please leave a comment in YT ticket and we will reconsider it.
