### ISSUE TITLE
Is there any plan to support Property,Method etc. as alternatives to phpdoc? 

### ISSUE THREAD

**Issue by dustinfog** [JetBrains/phpstorm-attributes#4]
In the past, we took  advantage of magic methods to simplicify our development, and as metadata, we parse the @properties and @methods from phpdoc into php code. Without syntax support,  these are fragile. I am exploring to replace these to Attibutes, but which are inconvenient after losing IDE support.
So, I was wondering if it's possible that you can implement this feature.

**Comment by wbars** [comment]
Hello, thanks for the idea! Right now I don't see how we can elevate attribute syntax to provide more strict syntax checks since nothing from method signature can be used inside attribute as valid PHP code. I will close this request, but this will remain in this tracker and may be reconsidered if new ideas will arrive here.
